### ISSUE TITLE
Add API support for row comment CRUD 

### ISSUE THREAD

**Issue by noahmercado** [googleapis/python-area120-tables#133]
It would be great to be able to programmatically read, write, and delete row comments either via the Google Apps Script advanced service or via the client SDKs.

`comments: [{}]` could either be an additional attribute of [`google.area120.tables_v1alpha1.types.Row`](https://googleapis.dev/python/area120tables/latest/tables_v1alpha1/types.html#google.area120.tables_v1alpha1.types.Row) and be added in with the existing methods for managing rows, or `google.area120.tables_v1alpha1.types.Comment` could become a standalone type that has a `parentId` == the row ID.

**Comment by busunkim96** [comment]
Hi @noahmercado,

I see you're a Googler. Please direct any feature requests for the API to the Area 120 Tables team directly. This library is generated from API protos (open source copy in [googleapis/googleapis](https://github.com/googleapis/googleapis)), so a feature added in the protos will automatically trickle down into the client library implementations in various languages.

**Comment by noahmercado** [comment]
Thanks @busunkim96 ! I'll reach out internally

**Comment by parthea** [comment]
Closing as a response was provided in https://github.com/googleapis/python-area120-tables/issues/133#issuecomment-1071038392
